### ISSUE TITLE
Publish the source code

### ISSUE THREAD

**Issue by ca-d** [OpenEnergyTools/scl-wizarding#1]
There's no source code in this repo, is this being developed somewhere else? I'd love to read what it currently does, but the compiled js is quite hard to grok.

**Comment by ca-d** [comment]
I'll get on a big refactor of this sometime in the next 2-3 weeks and prepare it for release to the public. Currently it's very much in a prototype stage.

**Comment by JakobVogelsang** [comment]
Is published. Please use with care as not tested and very likely buggy
