### ISSUE TITLE
Bay wizards don't prevent or advise for duplicates

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-wizarding#3]
The bay wizards (and perhaps other wizards) don't currently disallow creating an identical component of the same name which is already at the same depth in the hierarchy.

![image](https://github.com/OpenEnergyTools/scl-wizarding/assets/674783/8c5a8111-7fb6-4c6e-9c9c-812db7c16506)

This causes unintended consequences in the designer editor (presumably because it has the same identity or something similar).

Ideally this would be disallowed (greyed out) or at least flagged to the end user.

**Comment by JakobVogelsang** [comment]
Should be implemented @danyill .

**Comment by danyill** [comment]
That is the best! Thank you 👏 

![image](https://github.com/OpenEnergyTools/scl-wizarding/assets/674783/28e81451-b628-4a7e-9408-9f353b55e4a4)
